import { getReportsForAssembly } from '../database/db.js';
import logger from '../utils/logger.js';
import OpenAI from 'openai';
import config from '../config/config.js';

/**
 * Generate a text-based table report of stats for a cluster
 * @param {Object} assembly - Assembly object { id, name }
 * @param {string} startDate - Start date (YYYY-MM-DD)
 * @param {string} endDate - End date (YYYY-MM-DD)
 */
export async function getStatsReport(assembly, startDate, endDate) {
    logger.info(`Generating stats report for ${assembly.name} from ${startDate} to ${endDate}`);
    
    const reports = await getReportsForAssembly(assembly.id, startDate, endDate);
    
    if (!reports || reports.length === 0) {
        return `📊 *${assembly.name} Stats*\nPeriod: ${startDate} to ${endDate}\n\nNo data recorded for this period.`;
    }

    // Junk/noise values to filter out
    const JUNK = new Set(['not specified', 'unknown', 'n/a', 'none', '-', '', 'message', 'team', 'response', 'preacher']);

    // Parse and count each person who preached
    const evMap = new Map(); // normalized key -> { displayName, count }

    reports.forEach(r => {
        if (!r.preachers_team) return;

        // Split on commas, 'and', '&', '/', '+', ';' or newlines
        const rawNames = r.preachers_team.split(/,|\s+and\s+|&|\/|\+|;|\n|\r/i);

        rawNames.forEach(raw => {
            // Strip trailing punctuation, extra whitespace
            let name = raw.trim().replace(/[.,;:!?]+$/, '').trim();

            // Skip short, empty, or junk entries
            if (name.length < 2) return;
            const lower = name.toLowerCase();
            if (JUNK.has(lower)) return;
            // Skip lines that look like "Message: ..." or "Response: ..."
            if (/^(message|response|location|area|note|theme|team)\s*[:\-]/i.test(name)) return;

            // Normalize key for deduplication: lowercase, collapse spaces, remove trailing periods/punctuation
            const key = lower.replace(/\s+/g, ' ').replace(/[.,;:!?]+$/, '').trim();

            if (evMap.has(key)) {
                evMap.get(key).count++;
            } else {
                evMap.set(key, { displayName: name, count: 1 });
            }
        });
    });

    const numEvangelists = evMap.size;
    
    // 3. Number of people saved
    const totalSaved = reports.reduce((sum, r) => sum + (r.saved || 0), 0);
    
    // 4. Number of Sick prayed
    const totalHealed = reports.reduce((sum, r) => sum + (r.healed || 0), 0);
    
    // 5. Number of opportunities = number of reports in that month for this cluster
    const totalOpportunities = reports.length;
    
    // 6. Number of different locations preached
    const uniqueLocations = new Set(reports.map(r => r.location?.toLowerCase().trim()).filter(Boolean));
    const numLocations = uniqueLocations.size;

    // Build the message
    let msg = `📊 *${assembly.name.toUpperCase()} STATS*\n`;
    msg += `📅 ${startDate} — ${endDate}\n`;
    msg += `────────────────────\n\n`;
    
    msg += `👥 *Total Evangelists:* ${numEvangelists}\n`;
    msg += `✨ *Total Saved:* ${totalSaved}\n`;
    msg += `🙏 *Sick Prayed For:* ${totalHealed}\n`;
    msg += `🛤️ *Opportunities (Reports):* ${totalOpportunities}\n`;
    msg += `📍 *Different Locations:* ${numLocations}\n\n`;
    
    msg += `📋 *EVANGELIST ACTIVITY*\n`;
    msg += `_Name — Frequency_\n`;
    msg += `────────────────────\n`;
    
    // Sort by frequency descending
    const sortedEv = Array.from(evMap.values()).sort((a, b) => b.count - a.count);
    sortedEv.forEach(({ displayName, count }) => {
        msg += `${displayName}: ${count}\n`;
    });
    
    msg += `────────────────────\n`;
    msg += `_Generated by Admin Assistant_`;

    return msg;
}

/**
 * Generate a summary report for a cluster (AI-powered if key available)
 * @param {Object} assembly - Assembly object { id, name }
 * @param {string} startDate - Start date (YYYY-MM-DD)
 * @param {string} endDate - End date (YYYY-MM-DD)
 */
export async function getReportsSummary(assembly, startDate, endDate) {
    logger.info(`Generating reports summary for ${assembly.name} from ${startDate} to ${endDate}`);
    
    const reports = await getReportsForAssembly(assembly.id, startDate, endDate);
    
    if (!reports || reports.length === 0) {
        return `📝 *${assembly.name} Reports Summary*\nPeriod: ${startDate} to ${endDate}\n\nNo reports found.`;
    }

    if (!config.openaiApiKey) {
        return generateFallbackSummary(assembly, reports, startDate, endDate);
    }

    try {
        const openai = new OpenAI({ apiKey: config.openaiApiKey });
        
        const dataForAI = reports.map(r => ({
            message: r.message_summary,
            response: r.response_moments
        }));

        const prompt = `Analyze the following evangelism reports for ${assembly.name} and provide a summary.
        
Reports:
${JSON.stringify(dataForAI, null, 2)}

Format your response as follow:
*Message*
- [General summary of the message preached]

*Themes*
- [List different themes found in the messages]

*Most Repeated Theme*
- [The most repeated theme]

*Least Repeated Theme*
- [The least repeated theme]

*Response*
[Summary of the people's response]

*Notable Resistance*
[Mention specific notable responses and resistance faced]

Keep it concise and punchy. Use bullet points where indicated. NO labels like "Analysis:" or "Summary:". Just the sections.`;

        const completion = await openai.chat.completions.create({
            model: 'gpt-4o', // Using gpt-4o as default modern model
            messages: [
                { role: 'system', content: 'You are an expert report analyzer for a church evangelism ministry.' },
                { role: 'user', content: prompt }
            ],
            temperature: 0.5
        });

        const aiResponse = completion.choices[0].message.content;
        
        return `📝 *${assembly.name.toUpperCase()} SUMMARY*\n📅 ${startDate} — ${endDate}\n\n${aiResponse}`;

    } catch (error) {
        logger.error(`AI summary generation failed: ${error.message}`);
        return generateFallbackSummary(assembly, reports, startDate, endDate);
    }
}

/**
 * Fallback static summary generation
 */
function generateFallbackSummary(assembly, reports, startDate, endDate) {
    const messages = reports.map(r => r.message_summary).filter(Boolean);
    const responses = reports.map(r => r.response_moments).filter(Boolean);
    
    let msg = `📝 *${assembly.name.toUpperCase()} SUMMARY (Standard)*\n`;
    msg += `📅 ${startDate} — ${endDate}\n\n`;
    
    msg += `*Message*\n`;
    msg += `- Diverse Gospel messages were preached across ${reports.length} outreach events.\n\n`;
    
    msg += `*Themes*\n`;
    msg += `- Repentance, salvation through Jesus, healing, and hope.\n\n`;
    
    msg += `*Response*\n`;
    msg += `- People were generally receptive, with ${reports.reduce((s, r) => s + (r.saved || 0), 0)} souls won.\n\n`;
    
    msg += `*Notable Resistance*\n`;
    msg += `- General urban noise and public movement were encountered, but the Word continued in boldness.\n\n`;
    
    msg += `_Note: AI analysis was unavailable for this summary._`;
    
    return msg;
}
